nome = str(input('Digite o seu nome: ')).strip()
print(f'O seu nome em maiusculo: {nome.upper()}')
print(f'O seu nome em minusculo: {nome.lower()}')
print(f'Quantas letras ao todo: {len(nome) - nome.count(" ")}')
separa = nome.split()
print(f'O seu primeiro nome é {separa[0]} e ele tem {len(separa[0])} letras')
